const englishDateParts: Array<[RegExp, string]> = [
  [/\bJanuary\b/gi, "იანვარი"],
  [/\bFebruary\b/gi, "თებერვალი"],
  [/\bMarch\b/gi, "მარტი"],
  [/\bApril\b/gi, "აპრილი"],
  [/\bMay\b/gi, "მაისი"],
  [/\bJune\b/gi, "ივნისი"],
  [/\bJuly\b/gi, "ივლისი"],
  [/\bAugust\b/gi, "აგვისტო"],
  [/\bSeptember\b/gi, "სექტემბერი"],
  [/\bOctober\b/gi, "ოქტომბერი"],
  [/\bNovember\b/gi, "ნოემბერი"],
  [/\bDecember\b/gi, "დეკემბერი"],
  [/\bJan\b/gi, "იან"],
  [/\bFeb\b/gi, "თებ"],
  [/\bMar\b/gi, "მარ"],
  [/\bApr\b/gi, "აპრ"],
  [/\bJun\b/gi, "ივნ"],
  [/\bJul\b/gi, "ივლ"],
  [/\bAug\b/gi, "აგვ"],
  [/\bSep\b/gi, "სექ"],
  [/\bOct\b/gi, "ოქტ"],
  [/\bNov\b/gi, "ნოე"],
  [/\bDec\b/gi, "დეკ"],
  [/\bMonday\b/gi, "ორშაბათი"],
  [/\bTuesday\b/gi, "სამშაბათი"],
  [/\bWednesday\b/gi, "ოთხშაბათი"],
  [/\bThursday\b/gi, "ხუთშაბათი"],
  [/\bFriday\b/gi, "პარასკევი"],
  [/\bSaturday\b/gi, "შაბათი"],
  [/\bSunday\b/gi, "კვირა"],
  [/\bMon\b/gi, "ორშ"],
  [/\bTue\b/gi, "სამ"],
  [/\bWed\b/gi, "ოთხ"],
  [/\bThu\b/gi, "ხუთ"],
  [/\bFri\b/gi, "პარ"],
  [/\bSat\b/gi, "შაბ"],
  [/\bSun\b/gi, "კვ"],
];

export const normalizeGeorgianDateLabel = (value: string) =>
  englishDateParts.reduce(
    (current, [pattern, replacement]) => current.replace(pattern, replacement),
    value
  );
